package com.rentradar.backend.domain;

import com.rentradar.backend.domain.type.MonetaryAmount;
import com.rentradar.backend.domain.type.TrendDirection;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * A stored 30-day price forecast for one location. Regenerated by a scheduled job,
 * never computed on the request path: recursive multi-step forecasting is the most
 * expensive operation in the system and its output changes slowly.
 */
@Document(collection = "trend_forecasts")
@CompoundIndex(
        name = "location_generated_unique",
        def = "{'locationId': 1, 'generatedAt': 1}",
        unique = true
)
public record MarketTrendForecast(

        @Id String id,

        @Indexed String marketId,

        @Indexed String locationId,

        int horizonDays,

        List<ForecastPoint> series,

        TrendDirection direction,

        /** Mean absolute error of the producing model on held-out data. */
        double mae,

        String modelVersion,

        Instant generatedAt
) {

    public MarketTrendForecast {
        Objects.requireNonNull(marketId, "marketId must not be null");
        Objects.requireNonNull(locationId, "locationId must not be null");
        Objects.requireNonNull(series, "series must not be null");
        Objects.requireNonNull(direction, "direction must not be null");
        Objects.requireNonNull(modelVersion, "modelVersion must not be null");
        Objects.requireNonNull(generatedAt, "generatedAt must not be null");

        if (horizonDays <= 0) {
            throw new IllegalArgumentException("horizonDays must be positive");
        }
        if (series.size() != horizonDays) {
            throw new IllegalArgumentException(
                    "series length " + series.size() + " does not match horizon " + horizonDays);
        }
        if (mae < 0.0) {
            throw new IllegalArgumentException("mae must not be negative");
        }

        series = List.copyOf(series);
    }

    /** One day of the forecast, with its prediction interval. */
    public record ForecastPoint(
            int day,
            MonetaryAmount value,
            MonetaryAmount lower,
            MonetaryAmount upper
    ) {
        public ForecastPoint {
            Objects.requireNonNull(value, "value must not be null");
            Objects.requireNonNull(lower, "lower must not be null");
            Objects.requireNonNull(upper, "upper must not be null");

            if (day < 1) {
                throw new IllegalArgumentException("day must be 1 or greater, was " + day);
            }
            if (lower.compareTo(upper) > 0) {
                throw new IllegalArgumentException("lower must not exceed upper on day " + day);
            }
        }
    }
}